### ISSUE TITLE
weak hardware = never generating and working

### ISSUE THREAD

**Issue by thepotatolover** [nikolan123/Orbi#5]
if hardware is too weak it will try to generate multiple at once but never actually update the info in the web ui leading to the info never existing and being displayed

**Comment by nikolan123** [comment]
as i said in the readme, it will struggle with lower-end hardware
try to make the interval higher

**Comment by thepotatolover** [comment]
after this issue happened it now doesnt use ocr or generate with ai or take new screenshots after the first start

**Comment by nikolan123** [comment]
try setting the interval in config.json to at least 180 and restart both scripts

**Comment by thepotatolover** [comment]
i have set it too 300 and still isnt using ocr or ai

**Comment by nikolan123** [comment]
if it shows n/a that means its probably still generating or it was interrupted, are you sure you're not just impatient?

**Comment by thepotatolover** [comment]
how is 10% cpu usage on cpu only ai and ocr it working

**Comment by thepotatolover** [comment]
it doesnt even take more then 1 screenshot now and thats the one when you first launch capture.py

**Comment by nikolan123** [comment]
i just tried it on my old 1135g7 laptop which should be worse than your 3700u and it works thought its a bit slow, it took 175 seconds for one capture. are you sure you have only one instance running and you dont have other intensive stuff in the background? looking at the code again i dont see why it shouldnt work, you can try adding prints to see where it fails

**Comment by nikolan123** [comment]
issue found via discord, potato wasnt runningg right ollama command
